swagger: "2.0"
info:
  title: "S@fe - OpenAPI"
  version: "1.0.0"
  description: |-
    A very cool web app in which you can provide video data (webcam/video file) to be scanned for traffic signs.
    - [S@fe Github Repo](https://github.com/dinosaph/TraSD-LoCALisation)
tags:
  - name: scan
    description: Operations related to the traffic sign scanner
  - name: main
    description: Main operations - related to webpages
schemes:
- "https"
- "http"
paths:
  /home:
    get:
      tags:
      - main
      summary: Web page - Home
      description: Get main web page
      operationId: getHome
      produces:
      - "text/html"
      responses:
        '200':
          description: Successful operation
  /about:
    get:
      tags:
      - main
      summary: Web page - About
      description: Get about project page
      produces:
      - "text/html"
      responses:
        '200':
          description: Successful operation
  /contact:
    get:
      tags:
      - main
      summary: Web page - Contact
      description: Get the contact page
      produces:
      - "text/html"
      responses:
        '200':
          description: Successful operation
  /scan:
    get:
      tags:
      - main
      summary: Web page - Scan
      description: Get detection data for provided video data
      produces:
      - "text/html"
      responses:
        '200':
          description: Successful operation
    post:
      tags:
      - scan
      summary: Scanner operation - Upload file
      description: Post video data for scanning - file
      operationId: scanFile
      produces:
      - "application/json"
      consumes:
      - "application/octet-stream"
      responses:
        '200':
          description: Successful operation
        '405':
          description: Invalid input
  /scan/report:
    get:
      tags:
      - scan
      summary: Scanner operation - Get report
      description: Scanner operation - Get report
      operationId: getReport
      produces:
      - "application/json"
      responses:
        '200':
          description: Successful operation
  /scan/connect-to-classifier:
    post:
      tags:
      - scan
      summary: Scanner operation - Connection to Classifier
      operationId: connectClassifier
      produces:
      - "application/json"
      responses:
        '200':
          description: Successful operation