# Generated by Django 3.2.12 on 2022-02-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField(help_text='Enter traffic sign title', verbose_name='Class ID')),
                ('country', models.CharField(help_text='Enter origin country. (E.g.: Romania)', max_length=30, verbose_name='Country')),
            ],
            options={
                'ordering': ['-class_id'],
                'unique_together': {('class_id', 'country')},
            },
        ),
    ]
