# Generated by Django 3.2.12 on 2022-02-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficsign',
            name='country',
            field=models.CharField(choices=[('RO', 'Romania')], default='RO', max_length=2, verbose_name='Country'),
        ),
    ]
